name: Gradle Package

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Release Version'
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        
    - name: Grant Permission to Execute Gradle
      run: chmod +x gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        arguments: build

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to maven central
      run: |
        ./gradlew publish --no-daemon --no-parallel
        ./gradlew closeAndReleaseRepository
      env:
        ORG_GRADLE_PROJECT_VERSION_NAME: ${{ github.event.inputs.versionName }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
